# Generated by Django 2.2 on 2022-07-07 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='submitted_code',
            field=models.CharField(max_length=1000),
        ),
    ]
