# Generated by Django 2.2 on 2022-07-08 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0002_auto_20220707_0605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='submitted_code',
            field=models.TextField(default='something'),
        ),
    ]
